# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ac487b09b97b77469c4d086c837551e50980ce9ef588321807a908f3590288249faad50a933bff12dfe3624d5925ea931748badaf3f8dc8e34bd7cc8af9ab81

test:
  secret_key_base: 035f923630098b6b7ac49886a7104d9396f73836928c243db4db8a7d57b68e857c18699bd0f0589345d93dd3502cf3e034af7e7aecbe5264796b3d2b9a3af85a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
